# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    APP_ENV: '%env(APP_ENV)%'
    APP_SECRET: '%env(APP_SECRET)%'
    CORS_ALLOW_ORIGIN: '%env(CORS_ALLOW_ORIGIN)%'
    DATABASE_URL: '%env(DATABASE_URL)%'
    MEMCACHED_URL: '%env(MEMCACHED_URL)%'
    IMPORTER_CACHE_PATH: '%kernel.cache_dir%/../'
    GUEST_USER_ID: '%env(GUEST_USER_ID)%'
    SF_MR_CLIENTID: '%env(SF_MR_CLIENTID)%'
    SF_MR_COMPANYID: '%env(SF_MR_COMPANYID)%'
    SF_MR_USERNAME: '%env(SF_MR_USERNAME)%'
    SF_MR_PASSWORD: '%env(SF_MR_PASSWORD)%'
    SF_MR_API_URL: '%env(SF_MR_API_URL)%'
    SF_MR_API_VERSION: '%env(SF_MR_API_VERSION)%'
    SF_MR_APPLICATIONURL_EXTERNAL_PREFIX: '%env(SF_MR_APPLICATIONURL_EXTERNAL_PREFIX)%'
    SF_MR_APPLICATIONURL_INTERNAL_PREFIX: '%env(SF_MR_APPLICATIONURL_INTERNAL_PREFIX)%'
    SF_MR_APPLICATIONURL_FRIEND_PREFIX: '%env(SF_MR_APPLICATIONURL_FRIEND_PREFIX)%'
    SF_MR_AUTHENTICATION_URL: '%env(SF_MR_AUTHENTICATION_URL)%'
    JB_MR_IMPORTER_URL: '%env(JB_MR_IMPORTER_URL)%'
    SF_MR_PREFIX: '%env(SF_MR_PREFIX)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    okpt\my\web\page\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones