<?php

namespace ContainerXndyOwb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_ResetterService extends okpt_my_web_page_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.resetter' shared service.
     *
     * @return \FOS\ElasticaBundle\Index\Resetter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Index/ResetterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Index/Resetter.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Index/AliasProcessor.php';

        $a = ($container->privates['fos_elastica.mapping_builder'] ?? $container->load('getFosElastica_MappingBuilderService'));

        if (isset($container->privates['fos_elastica.resetter'])) {
            return $container->privates['fos_elastica.resetter'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['fos_elastica.resetter'])) {
            return $container->privates['fos_elastica.resetter'];
        }

        return $container->privates['fos_elastica.resetter'] = new \FOS\ElasticaBundle\Index\Resetter(($container->privates['fos_elastica.config_manager'] ?? $container->load('getFosElastica_ConfigManagerService')), ($container->privates['fos_elastica.index_manager'] ?? $container->load('getFosElastica_IndexManagerService')), ($container->privates['fos_elastica.alias_processor'] ?? ($container->privates['fos_elastica.alias_processor'] = new \FOS\ElasticaBundle\Index\AliasProcessor())), $a, $b);
    }
}
